### ISSUE TITLE
Authors in DESCRIPTION

### ISSUE THREAD

**Issue by datawookie** [eschoie26/legaldrink#1]
You need to provide more information on the package authors. Here's a good example of how that can be done:

https://github.com/judyh97/TimePackage/blob/master/DESCRIPTION

Although note in the example above I think that all of the people listed should be both "aut" and "cre" since they have made comparable contributions to the package.

**Comment by datawookie** [comment]
Thanks for addressing that. It's generally considered polite to give a short text response to somebody who has taken the time to give you feedback on your work. :) Just for future reference. This will ensure that they continue to provide you with helpful feedback.

**Comment by eschoie26** [comment]
Thank you for your feedback! Will review other feedbacks later this weekend after I get through other exercises

**Comment by datawookie** [comment]
No pressure. I know that you all have a lot on your plates.
